[package]
name = "defai_mint"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29.0"
mpl-token-metadata = { version = "1.11.0", features = ["no-entrypoint"] }


[lib]
crate-type = ["cdylib", "lib"]

