[programs.localnet]
defai_mint = "DeFA111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"  # Anchorのpackageレジストリ

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
